data_base:
  host: "localhost"
  port: "5432"
  username:
  password:
  dbname: "bookmarks"
  sslmode: "disable"
  driver: "pgx"

http_server:
    address: "localhost:8086"
    read_timeout: "10"
    write_timeout: "10"
    max_header_bytes: "1"

grpc_server:
    address: "localhost:8091"
    gateway_address: "localhost:8090"
    read_timeout: "10"
    write_timeout: "10"
    max_header_bytes: "1"


migrations_dir: "../internal/db/migrations/"
