data_base:
  host: "localhost"
  port: "5432"
  username: "admin"
  password: "hesoyam321!"
  dbname: "notes"
  sslmode: "disable"
  driver: "pgx"

http_server:
    address: "localhost:8081"
    read_timeout: "10"
    write_timeout: "10"
    max_header_bytes: "1"

grpc_server:
    address: "localhost:8082"
    read_timeout: "10"
    write_timeout: "10"
    max_header_bytes: "1"

grpc_gateway:
    address: "localhost:8083"
    read_timeout: "10"
    write_timeout: "10"
    max_header_bytes: "1"


migrations_dir: "../internal/db/migrations/"
# salt for password hashing (to .env)
# jwt_signing (to .env)


