data_base:
  host: "ns-postgres"
  port: "5432"
  username: "admin"
  dbname: "notes"
  sslmode: "disable"
  driver: "pgx"

redis:
  address: "ns-redis:6379"
  db: 0

http_server:
    address: "localhost:8081"
    read_timeout: 20s
    write_timeout: 20s
    max_header_bytes: 1048576

grpc_server:
    address: "localhost:8082"

grpc_gateway:
    address: "localhost:8083"


migrations_dir: "./internal/db/migrations/"


